#!/usr/bin/env python3
"""Generate cpp/server/src/op_gen.h from packet_opcodes.csv.

The CSV is extracted from RegisterAllPackets in the live client, so it is the
authority on both opcode numbers and sizes. Three entries come out of the
extractor as GENERIC*/unnamed because the registration site does not carry a
string; Melia's Op.cs has real names for those, and cross-checking the two
tables showed they agree on all 1259 entries otherwise, so borrowing the names
is safe.

    python gen_op_h.py
"""
import csv
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(ROOT, "packet_opcodes.csv")
OUT = os.path.join(ROOT, "cpp", "server", "src", "op_gen.h")
MELIA = os.path.join(os.path.dirname(ROOT), "Melia-master", "src", "Shared",
                     "Network", "Op.cs")

# Extractor fell back to a generic label; take the client-matching name from
# Melia, which agrees with our table on every other opcode.
RENAME = {
    21001: "ZC_INTERACTION_INFO",
    21002: "CZ_INTERACTION_CANCEL",
    21003: "ZC_INTERACTION_RIDE_USE_SKILL",
}

# Sizes our extractor read as 0 (variable) that the client actually declares.
SIZE_FIX = {21002: 64}


def main():
    rows = []
    with open(CSV, newline="") as f:
        for r in csv.DictReader(f):
            op = int(r["opcode_dec"])
            name = RENAME.get(op, r["name"])
            size = SIZE_FIX.get(op, int(r["size"]))
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
                name = "OP_%d" % op
            rows.append((op, name, size))
    rows.sort()

    seen = {}
    for i, (op, name, size) in enumerate(rows):
        if name in seen:
            name = "%s_%d" % (name, op)
            rows[i] = (op, name, size)
        seen[name] = op

    with open(OUT, "w", newline="\n") as f:
        f.write("// Generated by gen_op_h.py from packet_opcodes.csv -- do not edit.\n")
        f.write("//\n")
        f.write("// %d opcodes, extracted from RegisterAllPackets in the live client.\n"
                % len(rows))
        f.write("// kSize is the client's declared sizeof for the packet; 0 means the\n")
        f.write("// size is carried inline (u16 at +0x0A server->client, +0x16 client->server).\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace tos::op {\n\n")
        for op, name, size in rows:
            f.write("inline constexpr uint16_t %s = %d;%s\n"
                    % (name, op, "" if size == 0 else "  // size %d" % size))
        f.write("\n}  // namespace tos::op\n")

    print("wrote %s (%d opcodes)" % (OUT, len(rows)))


if __name__ == "__main__":
    main()
