#!/usr/bin/env python3
"""Generate properties.txt -- the property name/id table the zone server needs.

Property ids are the one piece of game data that is NOT readable out of the
client's .ies files: the client assigns them at runtime, and no shipped table
carries the mapping. They are taken from Melia's database instead, which was
checked against real traffic before being trusted -- see the verification at
the bottom of this script, which decodes a live ZC_OBJECT_PROPERTY out of
capture_1785545696.bin and resolves its ids against the generated table.

    python gen_properties.py [--verify]

Output format, one property per line, whitespace separated:

    <namespace> <name> <Number|String> <id>
"""
import argparse
import os
import re
import struct
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(os.path.dirname(ROOT), "Melia-master", "system", "db",
                   "properties.txt")
OUT = os.path.join(ROOT, "properties.txt")
CAPTURE = os.path.join(ROOT, "capture_1785545696.bin")

ENTRY = re.compile(
    r'\{ namespace: "(\w+)", name: "([^"]+)", type: "(\w+)", id: (\d+) \}')


def parse_source():
    with open(SRC, encoding="utf-8-sig") as f:
        text = f.read()
    return [(m.group(1), m.group(2), m.group(3), int(m.group(4)))
            for m in ENTRY.finditer(text)]


def write(entries):
    with open(OUT, "w", newline="\n", encoding="utf-8") as f:
        f.write("# Property name/id table for the zone server.\n")
        f.write("# Generated by gen_properties.py -- do not edit.\n")
        f.write("# Format: <namespace> <name> <Number|String> <id>\n")
        for ns, name, ty, pid in entries:
            f.write("%s %s %s %d\n" % (ns, name, ty, pid))


def verify(entries):
    """Resolve the ids in a captured ZC_OBJECT_PROPERTY against the table."""
    sys.path.insert(0, ROOT)
    import read_capture

    by_id = {}
    for ns, name, ty, pid in entries:
        by_id.setdefault(pid, []).append((ns, name))

    _, recs = read_capture.read(CAPTURE)
    packets = [r for r in recs if r.opcode == 3265]
    if not packets:
        print("no ZC_OBJECT_PROPERTY in the capture; skipping verification")
        return

    body = packets[0].body
    known = unknown = 0
    for off in range(16, min(len(body) - 8, 16 + 17 * 8), 8):
        pid = struct.unpack_from("<I", body, off)[0]
        if pid in by_id:
            known += 1
        else:
            unknown += 1
            print("  unresolved id %d" % pid)
    print("verify: %d of %d ids in the first captured ZC_OBJECT_PROPERTY "
          "resolve" % (known, known + unknown))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()

    entries = parse_source()
    write(entries)
    namespaces = sorted({e[0] for e in entries})
    print("wrote %s (%d properties, %d namespaces: %s)"
          % (OUT, len(entries), len(namespaces), ", ".join(namespaces)))

    if args.verify:
        verify(entries)


if __name__ == "__main__":
    main()
